#!/bin/bash

function mkcd {
	if [ ! -n "$1" ]; then
		echo "Enter a directory name"
	elif [ -d $1 ]; then
		cd $1
	else
		mkdir $1 && cd $1
	fi
}

mkcd scripts
echo 'require([deps/domReady],function(domReady){' > main.js
echo '	' >> main.js
echo '});' >> main.js
mkcd deps
curl https://raw.github.com/requirejs/domReady/latest/domReady.js > 'domReady.js'
curl https://raw.github.com/requirejs/text/latest/text.js > 'text.js'
curl https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.js > 'jquery.js'
curl http://code.angularjs.org/1.0.1/angular-1.0.1.js > 'angular.js'
curl https://github.com/downloads/SteveSanderson/knockout/knockout-2.1.0.debug.js > 'knockout.js'
cd ../..
mkcd build-tools
cd ..
mkcd less
echo '/** eric meyer reset **/' > styles.less
echo 'html, body, div, span, applet, object, iframe,h1, h2, h3, h4, h5, h6, p, blockquote, pre,a, abbr, acronym, address, big, cite, code,del, dfn, em, img, ins, kbd, q, s, samp,small, strike, strong, sub, sup, tt, var,b, u, i, center,dl, dt, dd, ol, ul, li,fieldset, form, label, legend,table, caption, tbody, tfoot, thead, tr, th, td,article, aside, canvas, details, embed, figure, figcaption, footer, header, hgroup, menu, nav, output, ruby, section, summary,time, mark, audio, video {font-family:sans-serif;margin: 0;padding: 0;border: 0;font-size: 100%;font: inherit;vertical-align: baseline;}article, aside, details, figcaption, figure, footer, header, hgroup, menu, nav, section {display: block;}body {line-height: 1;}ol.reset, ul.reset, ol.reset ol, ul.reset ul, ol.reset ul, ul.reset ol{list-style: none;}blockquote, q {quotes: none;}blockquote:before, blockquote:after,q:before, q:after {content: "";content: none;}table {border-collapse: collapse;border-spacing: 0;}' >> styles.less
cd ..
mkcd assets
cd ..
echo '<! doctype html >' > index.html
echo '<html><head>' >> index.html
echo '<title>test</title>' >> index.html
echo '<link rel="stylesheet/less" type="text/css" href="less/styles.less"><script src="less.js" type="text/javascript"></script>' >> index.html
echo '<script data-main="scripts/main" src="scripts/require.js"></script>' >> index.html
echo '<script type="text/javascript">require.config({paths: {"jquery": "deps/jquery"}})</script>' >> index.html
echo '<body>' >> index.html
echo '</body>' >> index.html
echo '</html>' >> index.html
git init
git submodule add git://github.com/jquery/sizzle.git ./scripts/deps/sizzle
git submodule add git://github.com/ded/reqwest.git ./scripts/deps/reqwest
git submodule add git://github.com/madrobby/zepto.git ./scripts/deps/zepto
git submodule add git://github.com/cloudhead/less.js.git ./scripts/deps/less
git submodule add git://github.com/documentcloud/backbone.git ./scripts/deps/backbone
git submodule add git://github.com/documentcloud/underscore.git ./scripts/deps/underscore
git submodule add git://github.com/wycats/handlebars.js.git ./scripts/deps/handlebars
git submodule add git://github.com/bestiejs/lodash.git ./scripts/deps/lodash
git submodule add git://github.com/jrburke/requirejs.git ./scripts/deps/require
git submodule add git://github.com/jrburke/r.js.git ./scripts/deps/r
git submodule init && git submodule update
ln -s sizzle/sizzle.js ./scripts/deps/sizzle.js
ln -s zepto/src/zepto.js ./scripts/deps/zepto.js
ln -s less/dist/less-1.3.0.js ./scripts/deps/less.js
ln -s backbone/backbone.js ./scripts/deps/backbone.js
ln -s underscore/underscore.js ./scripts/deps/underscore.js
ln -s lodash/lodash.js ./scripts/deps/lodash.js
ln -s handlebars/lib/handlebars.js ./scripts/deps/handlebars.js
ln -s reqwest/reqwest.js ./scripts/deps/request.js
ln -s ../scripts/deps/r/dist.js ./build-tools/r.js
ln -s deps/require/require.js ./scripts/require.js
